/**
 * Demo SSH Plugin — Frontend Entry Point
 *
 * This is a PRE-BUILT JS bundle that the plugin author ships.
 * It registers a Web Component (Custom Element) that the host app can use.
 *
 * In a real scenario, this file would be generated by building an Angular project:
 *   ng build --configuration=production
 *   The output would be a UMD/ESM bundle in dist/
 *
 * For this PoC, we manually write what the bundle would contain.
 */

// ─── Simulated Angular Component ───────────────────────────────────────────
// In reality, this would be an Angular component built with @Component decorator.
// The plugin author writes this in their own Angular project.

class DemoSshProfileFormElement extends HTMLElement {
  constructor() {
    super();
    this._form = null;
    this._shadow = this.attachShadow({mode: 'open'});
  }

  connectedCallback() {
    this.render();
  }

  // Called by host app to pass data into the element
  setForm(form) {
    this._form = form;
    this.render();
  }

  setProfile(profile) {
    this._profile = profile;
    this.render();
  }

  render() {
    this._shadow.innerHTML = `
      <style>
        :host { display: block; padding: 16px; }
        .form-field { margin-bottom: 12px; }
        label { display: block; font-size: 12px; color: #999; margin-bottom: 4px; }
        input, select { width: 100%; padding: 8px; border: 1px solid #444; border-radius: 4px;
                        background: #1e1e1e; color: #fff; font-size: 14px; box-sizing: border-box; }
        .plugin-badge { background: #ff9800; color: #000; padding: 2px 8px; border-radius: 4px;
                        font-size: 11px; display: inline-block; margin-bottom: 12px; }
      </style>
      <div class="plugin-badge">EXTERNAL PLUGIN</div>
      <h3 style="margin: 0 0 16px 0; color: #fff;">SSH Connection (Demo Plugin)</h3>
      <div class="form-field">
        <label>Host</label>
        <input type="text" id="host" placeholder="hostname or IP" />
      </div>
      <div class="form-field">
        <label>Port</label>
        <input type="number" id="port" value="22" />
      </div>
      <div class="form-field">
        <label>Username</label>
        <input type="text" id="username" placeholder="root" />
      </div>
      <div class="form-field">
        <label>Auth Type</label>
        <select id="authType">
          <option value="password">Password</option>
          <option value="sshKey">SSH Key</option>
        </select>
      </div>
    `;
  }
}

// ─── Register the Custom Element ────────────────────────────────────────────
// This is what makes the element available to the host app.
// The tag name must match manifest.json → frontend.profileFormElement

if (!customElements.get('demo-ssh-profile-form')) {
  customElements.define('demo-ssh-profile-form', DemoSshProfileFormElement);
}

// ─── Plugin Registration Interface ──────────────────────────────────────────
// The host app calls this to get plugin metadata.

window.__SSH_TERMINAL_PLUGIN__ = {
  manifest: {
    id: 'ssh-terminal',
    name: 'SSH Terminal (External)',
    category: 'TERMINAL',
    profileType: 'SSH_TERMINAL',
  },
  profileFormElement: 'demo-ssh-profile-form',
  version: '1.0.0',
};
